### ISSUE TITLE
This error

### ISSUE THREAD

**Issue by pwall2222** [ihaveamac/discord-mod-mail#12]
![Screenshot_1](https://user-images.githubusercontent.com/34860495/58045257-39d79b00-7b42-11e9-93ae-7938c75fb5cd.png)
I'm in another computer that runs on 32bits

**Comment by ihaveamac** [comment]
WinError 2 means "The system cannot find the file specified". What this should probably do is ignore errors related to the git command.

**Comment by pwall2222** [comment]
I know is file not found but, it closes the program.

**Comment by pwall2222** [comment]
What i have to do

**Comment by ihaveamac** [comment]
https://github.com/ihaveamac/discord-mod-mail/releases/tag/v1.2.1
