### ISSUE TITLE
DMs not relaying to channel

### ISSUE THREAD

**Issue by ImGoingSpace** [ihaveamac/discord-mod-mail#3]
if i send a dm to the bot, it is not relayed to the specified channel, it is however posting and listening to commands from the channel.
can you assist in this case?

**Comment by ihaveamac** [comment]
make sure `channel_id` is set to the right channel, and the bot can send messages to it.

also, don't make your bot token public(seen in one of your repos with mod-mail).

**Comment by ImGoingSpace** [comment]
yeah it can send / recieve commands from the channel. it just isnt relaying PMs sent to it.

Appreciate the reply, thanks!

**Comment by ihaveamac** [comment]
check the output of the terminal when a DM is sent to the bot. are there any errors?

**Comment by ImGoingSpace** [comment]
the only exception i'm getting is this, which is odd. AttributeError: module 'discord' has no attribute 'Embed'

**Comment by ihaveamac** [comment]
how did you install discord.py?

**Comment by ImGoingSpace** [comment]
well thats the thing, i'm not hosting it on a local machine, its running on heroku. i'll look into that more. thanks for the pointers :)

**Comment by ihaveamac** [comment]
install the latest version from pypi. using pip: `pip3 install discord.py`

**Comment by ImGoingSpace** [comment]
yeah it was outdated. typical. sorry to bug you. thanks for your input.
