### ISSUE TITLE
Cant import discord python error.

### ISSUE THREAD

**Issue by pwall2222** [ihaveamac/discord-mod-mail#8]

**Comment by ihaveamac** [comment]
discord.py is needed. I realize I forgot to put this in the README.

**Comment by pwall2222** [comment]
I give u a bat
[install.zip](https://github.com/ihaveamac/discord-mod-mail/files/3194508/install.zip)
And give the web https://www.python.org/ftp/python/3.6.8/python-3.6.8-amd64.exe for installing Python first

**Comment by pwall2222** [comment]
https://cdn.discordapp.com/attachments/573531730498289704/579414090653499394/Sin_titulo.png

**Comment by pwall2222** [comment]
That is the new error
