### ISSUE TITLE
This error.

### ISSUE THREAD

**Issue by pwall2222** [ihaveamac/discord-mod-mail#9]
https://cdn.discordapp.com/attachments/573531730498289704/579414090653499394/Sin_titulo.png

**Comment by pwall2222** [comment]
fatal: not a git repository (or any of the parent directories): .git
Checking for git commit failed: CalledProcessError Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.
fatal: not a git repository (or any of the parent directories): .git
Checking for git branch failed: CalledProcessError Command '['git', 'rev-parse', '--abbrev-ref', 'HEAD']' returned non-zero exit status 128.

**Comment by ihaveamac** [comment]
Copy config.ini.example to config.ini, then edit it to add your token. Don't publish config.ini publicly.

**Comment by pwall2222** [comment]
I know the token and that is private, but the token how long is?
(look at my fork, I did repair your missing information issue)

**Comment by pwall2222** [comment]
I did leave the Token in and still gives the same error, and the config.ini is readen after so isn't the issue

**Comment by pwall2222** [comment]
Done, my fail. Look at my fork.
